version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pl.project13.maven:git-commit-id-plugin
    versions:
    - 4.0.3
